# Scenario Planning Process {#chapter2}

Metropolitan land use and transportation scenario planning is a powerful process for better understanding the long-term impacts of today’s policy and investment decisions. Scenario planning allows a community to evaluate the likely outcomes of existing plans and to explore possible benefits and costs of alternative futures. Whether scenario planning is voluntary or mandatory for a metropolitan area, the process can help metropolitan areas make progress on a range of community goals, community needs and benefits, including GHG emission reduction. There is no one-size-fits-all prescription for scenario planning. Metropolitan areas are encouraged to design a scenario planning process that best addresses local conditions and builds on other concurrent or recent planning efforts.

## Establish scenario planning framework

A successful scenario planning process will rely on a sound organizing structure, local and community leadership and public support. Some of the major issues to address are who needs to be involved, what is the planning area, what organizational structure should be employed, who will be responsible for the technical work and analysis, how will funding be secured, who will be responsible for the financial and logistic aspects, and how will the process ensure broad participation.

Developing local support by involving local leaders gives the process credibility and helps maintain momentum during the process. In-depth interviews with stakeholders are valuable for identifying the topics that need to be addressed in addition to GHG emissions, and the networks available to engage the public in the process The various agencies, interest groups, the general public, and even any consultants who might be involved, will need to come together at the beginning of the process to identify and collaborate for a common purpose. Other potential aspects include using MPO’s for initiating a regional scenario planning process, or forming a new consortium in the absence of an already established process for reaching agreement in a metropolitan area.

Scenario assessment involves educating agency staff and technical advisory committees (TACs) on how to assess whether they are meeting their goals. This includes exploring what actions bring communities closer to meeting their GHG targets.

### Stakeholders

The process of carrying out scenario planning successfully involves building and maintaining a partnership from the outset. The various agencies, interest groups, the general public, and even any consultants who might be involved, will need to come together at the beginning of the process to identify and collaborate for a common purpose. For effective community engagement and investment, citizens and stakeholders must be able to trust the opinions and skills of the leadership. The leaders need to be able to effectively convey the benefits of scenario planning, the process and its potential outcomes. It is equally important that community members and stakeholders trust that the leadership believes scenario planning can make desirable changes for the community. There will be times where compromise is required. The process must be transparent and inclusive to ensure that the key partners will trust the process and support the outcomes.

The process should begin by designing an active, two-way approach to communicating with community members. Communication in terms of scenario planning should be a broad, double-sided style of engagement—true give and take between planners and the community that continues throughout the process.

The scale of public involvement effort will depend on the size of the metropolitan area and the scale of the scenario planning project. Agencies consider factors such as the level of the community’s involvement in past planning efforts, expected levels of community interest, the type of proposals likely to be considered in the scenario planning process and the available budget for outreach.

An important step can be to form a policy advisory committee that includes an array of local decision makers from participating jurisdictions (e.g., elected Officials or high-level staff person) or community representatives. The advisory committee can guide the process, represent local interests, and weigh in on key decisions points during the planning process.

In addition to the leaders and champions mentioned earlier, it may also be important for the region to engage with some or all of the following interests:

-   Community-based organizations and non-profits

-   Environmental organizations

-   Transit districts and transportation providers

-   Tribal leaders (if tribal lands are impacted)

-   Traditionally underserved and disadvantaged communities

-   Chambers of commerce

-   Hospitals and health care organizations

-   Public and private utilities

-   Development interests

-   Universities and schools

-   Freight

### Data and projects that inform the process

Scenario plans will be built from and continue efforts from previous regional and local transportation planning efforts. State and Federal plans can also inform and guide the scenario planning process. Some examples of projects and data to collect, review and pull from include (but are not limited to) the following documents or projects.

-   Metropolitan Planning Organization adopted Regional Transportation Plan and related regional travel demand model scenarios

-   City and County Transportation System Plans

-   City and County Comprehensive Plans

-   Local active transportation and transit plans

-   Local economic development plan

-   Population and employment forecasts

-   Transportation corridor or facility plan

-   Major project Environmental Impact Statements or Environmental Assessment

-   Oregon Statewide Transportation Strategy

-   Oregon Transportation Plan and Oregon Highway Plan

### Principles, issues and outcomes

A review of existing plans can uncover guiding principles, goals, objectives and issues identified in past planning efforts. These values and goals found in past planning efforts will help inform the development of guiding principles and future stakeholder engagement needs. An analysis of existing plans can reveal local and regional planning issues that could be also analyzed using VisionEval as part of a scenario planning process.

It is important to describe scenario planning in terms of community benefits and outcomes. Many community goals – such as livable communities, health concerns, safety for children and others, walking and biking – have the additional benefit of also reducing GHG emissions. Oregon communities have been actively engaged in conversations about land use and transportation for many years. Many ongoing or recurrent planning efforts will likely gain new interest and excitement from using the scenario planning process, and then can also lend their credibility and constituency to scenario planning.

### Strategies for GHG reductions

Strategies – or actions and investment methods – are employed at multiple levels to achieve specific outcomes. Strategies can be at any geographic scope or scale, such as overarching, targeted but general, or specific. For instance, an overarching strategy is regional, a targeted but general may be citywide and specific could refer to a neighborhood.

Table 2: Strategies based on geographical scope and scale

| **Strategy 1**                                                                                                                     |                                                                                                                                                                   |                                                                                                                                                                                         |
|------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Overarching**                                                                                                                    | **Targeted but general**                                                                                                                                          | **Specific**                                                                                                                                                                            |
| Prioritize centers to accommodate most of the future growth toward already developed metropolitan areas. Shown on the concept map. | Designate regional and town centers to support development of mixed-use areas. Shown on the concept map and tested by assigning growth in the technical scenario. | Design a small area plan (i.e., urban renewal to build housing downtown). Develop new ordinances and demonstration projects compatible with ordinances.                                 |
| **Strategy 2**                                                                                                                     |                                                                                                                                                                   |                                                                                                                                                                                         |
| **Overarching**                                                                                                                    | **Targeted but general**                                                                                                                                          | **Specific**                                                                                                                                                                            |
| Create a robust transit network. Shown on the concept map by major transit lines.                                                  | Increase in transit service – including more stops and increased frequency throughout the transit network.                                                        | Increase transit service for key corridors and improve first-last mile connections to transit stops.                                                                                    |
| **Strategy 3**                                                                                                                     |                                                                                                                                                                   |                                                                                                                                                                                         |
| **Overarching**                                                                                                                    | **Targeted but general**                                                                                                                                          | **Specific**                                                                                                                                                                            |
| Encourage a decrease in driving overall and at certain times.                                                                      | Propose fees for driving, such as vehicle registration or fuel tax. Propose Telework program based on advertising or financial incentives.                        | Build a key piece of infrastructure that improves non-driving modes (highway and BRT). Implement district or cordon pricing or facility tolling. Change land use density and diversity. |

VisionEval strategies are input using data and assumptions affecting both the land use and transportation elements. These “lever” adjustments to test are made in partnership with local agencies and planning partners often reflecting actions under consideration. Meetings with smaller groups of agency and transit staff is a key step to review reference future assumptions and identify more advanced actions, and associated data and assumptions in order to quantify the effects of those actions in the model. This step helps contextualize scenarios and alternative futures being tested with specific and on-the-ground knowledge regarding:

-   Public transportation service and bus electrification

-   shift single-occupant vehicle (SOV) travel to active transportation

-   parking pricing programs (e.g., proportion of workers who pay for parking)

-   mixed use and higher density development

-   driving efficiency through eco-driving, ITS deployment, etc.

-   travel demand management programs such as employee commute options

-   vehicle technology, zero emissions fuel

-   tolling and road pricing

## Develop Evaluation Criteria

One of the keys to scenario planning is clearly defining the outcomes that will signify the success of the project. Developing a set of guiding principles will help to identify and prioritize evaluation criteria that will be used later to assess and compare scenarios. Selection of guiding principles can serve as an early stakeholder and advisory committee engagement activity, and can help develop a set of evaluation criteria as a benchmark for scenario performance. Establishing evaluation criteria that resonate with members of the community is essential to a successful process. Effective evaluation criteria can be measured objectively and are meaningful to stakeholders. Evaluation criteria should address a range of community objectives such as public health, a stronger local economy, average household fuel expenditures, access to transit, access to bicycle and pedestrian routes, and preservation of natural areas, as well as GHG reduction.

#### Evaluation Criteria

The process of comparing multiple future scenarios should employ a set of criteria that addresses the full range of needs and desires expressed through the guiding principles. The best practice is to select evaluation criteria based on the guiding principles to prioritize what is important to the community. The final set of evaluation criteria should be drawn from measures established in existing plans, and calculated by the Regional Strategic Planning Model. ODOT currently uses the Place Types tool (<https://www.oregon.gov/lcd/CL/Pages/Place-Types.aspx>) to evaluate impacts based on several land use and housing attributes. Users can also defer to land use from their Regional Travel Model. The accompanying table presents a suggested set of criteria likely to support many guiding principles.

Table 3: Evaluation criteria, unit of measure, and source

| **EVALUATION CRITERIA**                                     | **UNIT OF MEASURE**                |
| ----------------------------------------------------------- | ---------------------------------- |
| **Land Consumption and Density**                            |                                    |
| Land Consumption                                            | acres                              |
| Density                                                     | housing units/ acre and jobs/ acre |
| Development uses                                            | square feet                        |
| Parking area                                                | square feet                        |
| **Housing and Affordability**                               |                                    |
| Housing mix by type (single-family, multi-family, townhome) | percent of units                   |
| Housing tenure (rental or ownership)                        | percent of units                   |
| Housing cost                                                | average rent and sales price       |
| Housing affordability by income level                       | number of units and % of units     |

| **Economy and Prosperity**            |                            |
| ------------------------------------- | -------------------------- |
| Employment by sector                  | \# and %                   |
| Housing and transportation costs      | \$ and % of average income |
| Development value                     | \$/ acre                   |
| Costs of providing parking spaces     | \$                         |
| Household and ownership costs         | \$                         |
| Fuel and electricity costs per capita | \$                         |

| **Transportation and Health**                                |                                                              |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| Light vehicle miles traveled *(e.g., total, per capita)*     | miles and miles/capita                                       |
| Vehicle delay (time lost due to congestion)                  | hours/ capita                                                |
| Travel mode split, average trip time, average trip distance  | % time and distance                                          |
| Accessibility to transit                                     | households and jobs within ¼ mile walking distance           |
| Transit service levels                                       | service miles/ capita                                        |
| Walkable areas                                               | households and jobs within areas of well-connected street or path networks |
| Complete neighborhoods                                       | ratio of households to jobs                                  |
| Households within walking distance of parks, schools, cultural amenities, etc. | households and %                                             |
| Fuel consumption                                             | gallons/capita                                               |
| Non-motorized travel pe capita                               | miles/capita                                                 |

| **Environment, Sustainability, and Public Health**           |                               |
| ------------------------------------------------------------ | ----------------------------- |
| Sensitive lands developed (growth in Goal Five lands, prime and secondary agricultural &forestry lands) | acres                         |
| Hazard mitigation (growth in hazard prone areas)             | acres                         |
| Building energy consumption                                  | btu/ housing unit or employee |
| GHG emissions (building and transportation emissions)        | tons CO2/ year                |

Source: Oregon Scenario Planning Guidelines

## Set Up Scenario Modeling (see Section 3.5)

This step of the scenario planning process begins by a geographic scale for analysis, compiling data and other information needed to create scenarios, and setting up the tools for scenario building.

A base year will need to be established as the starting point for scenario planning along with a planning horizon year representing an end date for the future scenarios. The model will require designation of a planning unit size, reflecting the geographic scale at which the scenarios will be designed. A part of the setup will be collecting data about existing conditions and plans in place, along with future forecasts. These steps are described further below.

### Base Year – Historical Basis for Comparison

Users of VisionEval must set inputs to calibrate the base year model, or the assumptions and data that best represent the currently existing conditions. All users should use a base year of 2005 which is in-line with the Target Rule. The base year provides a benchmark for comparison of existing conditions with the future year reference scenario and alternative future scenarios. The base year should be consistent with state, regional and local planning efforts to allow for developing a clear evaluation process and comparing results to other efforts. The state and most local jurisdictions will have available data for the base year. Additionally, a “reality check” should be conducted comparing the baseline against known local trends and projections.

Information is collected at three different geographic levels. Study Area defines the extent of the area included in the model. The study area may be partitioned into “divisions”, or A-zones, (population greater than 50,000) which define large portions of the metropolitan area which have different land use and transportation policies or where differing policies may be applied in the future. B-zones are the geographic unit used for assigning the projected households. B-zones are ordinarily defined as an aggregation of zones from a region’s travel demand model, that ideally align with Census block group boundaries (approximately 0 – 6,500 persons) to simplify input data collection and to match the geographic units used in model estimation to a place.

Within the local baseline assessment, land area is characterized by development type. A study area generally consists of a mix of metropolitan, town, and rural land areas. Most urban areas of the region are metropolitan, typically defined as all urbanized land within the urban growth boundary (UGB) of the MPO’s primary city or contiguous cities. Towns are typically less dense but still urbanized areas within the study area that fall outside of the UGB of MPO’s primary city or contiguous cities. All non-urbanized, less dense lands within the study area are rural.

#### Future Baseline Scenario

The future baseline scenario builds from the base year conditions to forecast how today’s plans and policies are likely to play out in the future planning year. The minimum future planning year for the reference case and alternative scenarios should be 2040. Because most local land use and transportation plans currently extend to this date, or close to it, making needed information readily available. The adopted metropolitan area GHG reduction targets are set for the years 2040 through 2050.

The reference case developed with the VisionEval will show the likely results of current adopted plans on the evaluation criteria in the future planning year. Performance of the reference case is evaluated initially using outputs from VisionEval and subsequent outputs from the other available tools that may be of interest to the region. Comparing the reference case to the base case, using a consistent set of evaluation criteria, will provide important perspective for community residents and stakeholders in understanding the magnitude of the changes anticipated. Locals should be encouraged to develop other scenarios that meet their GHG targets and additional local goals.

#### Combine VisionEval Outputs with Travel Demand Model

A VisionEval model can be better developed and validated if it is aligned by year with a travel demand model of the subject area. VisionEval may be used to model interim years, however each year modeled requires additional input data. Oregon MPOs setting up a VisionEval model are recommended to model the following years:

-   2005 – back-cast to match the MPO GHG reduction target base year.&nbsp;

-   2010 Base Year – basis for data collection, calibration, and other runs. Note: VE converts all financial outputs to base year values. The base year can be some other year with plentiful empirical data by which the model can be validated to.

-   2045 – the date associated with MPO GHG reduction targets.

-   2050 – the date associated with statutory GHG reduction goals. The longer time frame enables consideration of a wider horizon of possible changes.

-   Additional interim years can be helpful to see the full trajectory of change over time. This is helpful to understand policy transitions or meet goals tied to other years.

A key value of VisionEval is how it facilitates running many scenarios or possible futures. In practice, the user typically starts by setting up the model with a reference scenario, or best estimate of future conditions. The model can be calibrated to a historical year and then validated to another historical year. These reference scenarios serve as a pivot point for manual or automated scenario testing alternative. Typically, scenario testing includes a mix of the following, reflecting “what if” type questions:

-   Sensitivity tests (manual) – One at a time, change single “category” of a model input and explore a handful of model runs; This helps understand the impact of various policies in isolation on the outcomes of interest and

-   Combination Scenarios (can be automated) – Changes in multiple input “categories,” all combinations can be automatically run. A large set of scenarios can be further exported and explored in the VisionEval Scenario Viewer, an on-line interactive tool. For more sophisticated scenario analysis, VisionEval can be connected to TMIP-EMAT, further described in Chapter 7.2. See <https://rosap.ntl.bts.gov/view/dot/64646/dot_64646_DS1.pdf> for additional information for Transportation Planning for Uncertain Times: A Practical Guide to Decision Making Under Deep Uncertainty for MPOs.

### Develop and Evaluate Alternative Scenarios

Although many alternative scenarios can be developed in a short time with VisionEval, too many scenarios may make the differences between each difficult to understand, and too few scenarios may not present sufficient options for stakeholders.

The theme of a scenario is the basis, or focus, of its design. Themes can range from recent trends to modifications of the reference case (like improving jobs-to-housing balance), to those based on specific drivers (like housing or economic development forecasts). The selected scenario themes should be as distinct and diverse as possible. This process allows VisionEval users to examine how outcomes vary across scenarios, and examine distinct differences between them. By adjusting specific requirements, a community can simulate and then evaluate the impact of any number of policy choices. Other options for visualization include the TMIP-EMAT framework, which allows visualization of several hundred scenarios at once.

#### Scenario Theme Examples

**Recent trends:** The reference case scenarios developed may represent the future as depicted by local plans. However, since current trends may be diverging from the planned future, a scenario theme may also be based on recent trends.

**Land Use Changes:** A scenario such as this would be based on the premise that the transportation system and other policy tools remain the same as in the baseline assumptions. The purpose is to answer the question, “What is the most the metropolitan area could get from land use changes alone?

**Transportation Changes:** This theme uses ideas about transportation investments as the basis for its design. For example, this might include increasing transit service for the region or along key corridors, closing key gaps in active transportation infrastructure, and making the existing system more efficient.

**Specific Drivers:** A driver is a force that can change the future. For example, demographic changes impact the housing and transportation choices that individuals make. Using demographic forecasts as a driver, a scenario could be created based on a variant of projected future population growth.

**Specific Community Goals:** This scenario theme uses specific community goals to guide the design. For example this scenario could be crafted to address specific interests or needs identified by community members and stakeholder groups during engagement activities.

#### Evaluating the alternative scenarios

The performance of the alternative scenarios is measured using the evaluation criteria and the VisionEval Model. The recommended approach is to begin with a baseline assessment using the VisionEval Model to other available tools that may be of interest to the region. Each alternative scenario should be evaluated based on the same evaluation criteria used in the reference case evaluation for easy comparison. Additionally, a “reality check” should be conducted against known local trends and projections.

A meaningful process will draw connections to the characteristics of the scenarios. After scenario development, it is important to organize the evaluation criteria to provide context and discuss the significance of the data. A good strategy is to highlight the differences between the scenarios, not the absolute numbers. A review of the evaluation results and alternative scenarios should show what the future could look like based on the scenarios stakeholders played a role in designing.

##### Sensitivity Testing

Sensitivity testing is done to inform the Preferred Scenario and evaluate how changes in policies and trends at the metropolitan and state levels could influence GHG emissions from light-duty vehicle travel in metropolitan areas, as well as other indicators. Sensitivity tests are ‘what if’ analyses to help planners understand what the relative effect of changes to policy, investments, and programs could be. Depending on the variables used, sensitivity testing allows metropolitan areas to determine how large an effect potential actions that can be quite different in scope are likely to have on the desired outcomes. Sensitivity testing can be used to evaluate a wide range of variables such as the impact of increasing downtown density, doubling transit service, or promoting eco-driving, and compare those to the GHG effects of ITS policies, electrification, and pricing policies. ODOT has identified the following set of sensitivity tests. A recommended set will be customized for the local area, and reviewed with participants and other partners.

1.  Compact Land Use: More compact and mixed land use patterns

2.  Transit Investment: Increased transit service levels

3.  Light Vehicle Promotion: Increased shift of short-distance single-occupant vehicle (SOV); travel to bicycle, electric bicycle, and similar light-weight vehicles (e.g., scooters)

4.  Parking Policies: Availability, parking pricing programs (e.g. proportion of workers who pay for parking and/or employers implementing cash-out-buy-back programs)

5.  Driving Efficiency: Improving driving efficiency through eco-driving, ITS deployment, etc.

6.  Demand Management: Expanding travel demand management programs such as employee commute options, individualized marketing and car service availability

7.  Aggressive Vehicle/Fuels: Further improvements of vehicle technology, fleet and fuel characteristics identified in the STS (e.g. higher levels of adoption of PHEV and EV)

8.  Aggressive State Actions: Other state-level changes in pricing and other factors that influence vehicle travel and GHG emissions such as pay-as-you-drive (PAYD) insurance and user fees.

Each sensitivity test is represented by a small number of changes to reference case input files. Once the changes are made (e.g., changing the input regarding the proportion of households having pay-as-you-drive insurance). Automated procedures can be used to create scenarios that represent the possible combinations of inputs for testing (e.g. increasing transit service and improving travel demand management programs). The results of all these scenarios are then evaluated to show potential changes and synergies that can occur by combining various programs.

## Develop and identify a Preferred Scenario

Developing and identifying a preferred scenario requires a combination of public and stakeholder input and the evaluation results. The timeline and resources of such an effort can be significantly higher than the exploration of scenarios in a Strategic Assessment. The public and elected officials are likely to play a much larger role. The preferred scenario is a package that includes a expected outcomes, a set of major programs, policies or general actions, and spatially distributed future housing and employment estimates. Once the public has weighed in on their preferred elements of each of the alternative scenarios, the next step is to synthesize that input and translate it into a preferred scenario.

**Understanding input:** Public input responses on the alternate scenarios should be compiled and ranked. Identifying popular elements and themes will help to form the preferred scenario. The goal of understanding the community’s input is to identify areas of consensus and consider compatibility and tradeoffs among scenario elements and themes.

**Translating public input into a preferred scenario:** The scenario that most closely lines up with the rankings made by the public and the steering committee can be used as a starting point. It can be useful to build two or three technical scenarios that achieve similar desired outcomes but employ different themes or strategies. These additional scenarios can be used to illustrate the flexibility a community has to achieve the same outcomes but through different planning approaches.

**Refining scenarios with stakeholders:** The preferred scenario is not generally a selection of one of the initial scenarios as the best. Rather, it is a new scenario combining elements or strategies from various alternative scenarios and as such it may need to be adjusted to ensure that compatible elements are being used.

**Seeking guidance from elected officials:** Elected officials within the metropolitan area should be regularly engaged throughout the scenario planning process, especially where the results of public review are conflicting or ambiguous. Engagement should consist of sharing results at key milestones and engaging them in discussions on the project outcomes.
