# Future Scenario – Baseline Reference 

As discussed in Section 3.5, the future baseline reference scenario is meant to show current trends given no new or unexpected changes to transportation and land use within the model region beginning in 2005. This is meant to be used as a comparison scenario for model results.

The baseline reference scenario should use a combination of local/regional inputs and inputs specified under the Adopted Plans (AP 2022) reference scenario. The scenario typically uses the most recently adopted long range plan to establish the Socio-economic forecasts, land use changes, policies, and system investments.

The future baseline scenario will use the AP 2022 *VEPowertrainsAndFuels* package that includes the adopted plans trajectory for vehicles, powertrains, and fuels.

The purpose of this scenario is to provide an important datapoint to frame and contextualize the changes that are expected to occur in the absence of further action. It is been found to be helpful to run this scenario and compare it to the Target Rule Scenario discussed in Chapter 5.0.
